### PR TITLE
the number which is increasing while guessing the number that fixed

### PR DESCRIPTION
**Pull request by Biprotosh**
I just guess the number **4** time but it the program showing me **313** times.
I just changed the code little bit
_**Thank You!**_

Capture

### CODE REVIEW

**Comment by OsandaLakshitha** [comment]
I didn't had that problem when i compile this but thank you for fixing this

**Comment by Biprotosh** [comment]
hey if you don't mind can we talk on discord

**Comment by OsandaLakshitha** [comment]
yeah hit me on discord Garfield SL#3161

**Comment by Biprotosh** [comment]
already done just accept the friend request

**Pull request closed without merging**
